# Generated by Django 5.1.4 on 2025-01-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(default='sad', upload_to='devices/'),
            preserve_default=False,
        ),
    ]
