# Generated by Django 5.1.4 on 2025-01-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_device_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='_type',
            new_name='d_type',
        ),
    ]
