# Generated by Django 5.0 on 2024-09-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ST', 'Durnukly'), ('ER', 'Näsazlyk'), ('FC', 'Düzedilmez Ýagdaýda')], default='ST', max_length=2)),
                ('status_desc', models.TextField(blank=True, null=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devicetype')),
            ],
        ),
    ]
