# Generated by Django 5.0 on 2024-09-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'enjam', 'verbose_name_plural': 'enjamlar'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'enjam görnüşi', 'verbose_name_plural': 'enjam görnüşleri'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profiller'},
        ),
        migrations.AddField(
            model_name='devicetype',
            name='short',
            field=models.SlugField(default='hell', max_length=250, verbose_name='Gysgaltmasy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Maglumat'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devicetype', verbose_name='Enjam görnüşi'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(upload_to='devices/', verbose_name='Suraty'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ST', 'Durnukly'), ('ER', 'Näsazlyk'), ('FC', 'Düzedilmez Ýagdaýda')], default='ST', max_length=2, verbose_name='Ýagdaýy'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Ýagdaýy hakynda maglumat'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Ady'),
        ),
    ]
