# Generated by Django 5.0 on 2024-09-14 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_device_options_alter_devicetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'hünär', 'verbose_name_plural': 'hünärler'},
        ),
        migrations.AlterModelOptions(
            name='technicalwork',
            options={'verbose_name': 'tehniki iş', 'verbose_name_plural': 'tehniki işler'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialization', verbose_name='Hünäri'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='value',
            field=models.CharField(max_length=250, verbose_name='Hünäri'),
        ),
        migrations.AlterField(
            model_name='technicalwork',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Wagty'),
        ),
        migrations.AlterField(
            model_name='technicalwork',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.device', verbose_name='Enjam'),
        ),
        migrations.AlterField(
            model_name='technicalwork',
            name='report',
            field=models.TextField(verbose_name='Raport'),
        ),
        migrations.AlterField(
            model_name='technicalwork',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.profile', verbose_name='Işgär'),
        ),
    ]
