# Generated by Django 5.1.1 on 2025-01-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb', '0007_campusfirstinfocolumn_campussecondinfocolumn_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='DeviceType',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.RemoveField(
            model_name='campuspage',
            name='first_info_columns_block',
        ),
        migrations.RemoveField(
            model_name='campuspage',
            name='second_info_columns_block',
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={},
        ),
        migrations.RenameField(
            model_name='devicetype',
            old_name='fifth_year_students',
            new_name='fifth_year_production',
        ),
        migrations.RenameField(
            model_name='devicetype',
            old_name='first_year_students',
            new_name='first_year_production',
        ),
        migrations.RenameField(
            model_name='devicetype',
            old_name='fourth_year_students',
            new_name='fourth_year_production',
        ),
        migrations.RenameField(
            model_name='devicetype',
            old_name='second_year_students',
            new_name='second_year_production',
        ),
        migrations.RenameField(
            model_name='devicetype',
            old_name='third_year_students',
            new_name='third_year_production',
        ),
        migrations.DeleteModel(
            name='CampusFirstInfoColumn',
        ),
        migrations.DeleteModel(
            name='CampusPage',
        ),
        migrations.DeleteModel(
            name='CampusSecondInfoColumn',
        ),
    ]
